using System;

namespace EnterpriseSolutionBIDesktop
{
    public  partial class CompanyEntity
    {
        public CompanyEntity()
        {

        }

        public decimal RECNUM { get; set; }
        public string COMPANY_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string SUSPENDED { get; set; }
        public string DB_SERVER { get; set; }
        public string DB_DATABASE { get; set; }
        public string DB_USER { get; set; }
        public string DB_PASSWORD { get; set; }
        public string DB_DRIVER { get; set; }
        public string DB_REPT_DRIVER { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? REVISED_DATE { get; set; }
        public string REVISED_BY { get; set; }
        public string ACCT_ANLYS1_OPT { get; set; }
        public string ACCT_ANLYS2_OPT { get; set; }
        public string ACCT_ANLYS3_OPT { get; set; }
        public string ACCT_ANLYS4_OPT { get; set; }
        public string VOCH_ANLYS1_OPT { get; set; }
        public string VOCH_ANLYS2_OPT { get; set; }
        public string VOCH_ANLYS3_OPT { get; set; }
        public string VOCH_ANLYS4_OPT { get; set; }
        public string VOCH_ANLYS5_OPT { get; set; }
        public string VOCH_ANLYS6_OPT { get; set; }
        public string ITEM_ANLYS1_OPT { get; set; }
        public string ITEM_ANLYS2_OPT { get; set; }
        public string ITEM_ANLYS3_OPT { get; set; }
        public string ITEM_ANLYS4_OPT { get; set; }
        public string CUST_ANLYS1_OPT { get; set; }
        public string CUST_ANLYS2_OPT { get; set; }
        public string CUST_ANLYS3_OPT { get; set; }
        public string CUST_ANLYS4_OPT { get; set; }
        public string VEND_ANLYS1_OPT { get; set; }
        public string VEND_ANLYS2_OPT { get; set; }
        public string VEND_ANLYS3_OPT { get; set; }
        public string VEND_ANLYS4_OPT { get; set; }
        public string SALE_ANLYS1_OPT { get; set; }
        public string SALE_ANLYS2_OPT { get; set; }
        public string SALE_ANLYS3_OPT { get; set; }
        public string SALE_ANLYS4_OPT { get; set; }
        public string SALE_ANLYS5_OPT { get; set; }
        public string SALE_ANLYS6_OPT { get; set; }
        public string PURC_ANLYS1_OPT { get; set; }
        public string PURC_ANLYS2_OPT { get; set; }
        public string PURC_ANLYS3_OPT { get; set; }
        public string PURC_ANLYS4_OPT { get; set; }
        public string PURC_ANLYS5_OPT { get; set; }
        public string PURC_ANLYS6_OPT { get; set; }
        public string MVMT_ANLYS1_OPT { get; set; }
        public string MVMT_ANLYS2_OPT { get; set; }
        public string MVMT_ANLYS3_OPT { get; set; }
        public string MVMT_ANLYS4_OPT { get; set; }
        public string MVMT_ANLYS5_OPT { get; set; }
        public string MVMT_ANLYS6_OPT { get; set; }
        public DateTime? AREVISED_DATE { get; set; }
        public string AREVISED_BY { get; set; }
        public string JORD_ANLYS1_OPT { get; set; }
        public string JORD_ANLYS2_OPT { get; set; }
        public string JORD_ANLYS3_OPT { get; set; }
        public string JORD_ANLYS4_OPT { get; set; }
        public string JORD_ANLYS5_OPT { get; set; }
        public string JORD_ANLYS6_OPT { get; set; }
        public string VOCH_ANLYS7_OPT { get; set; }
        public string VOCH_ANLYS8_OPT { get; set; }
        public string SALE_ANLYS7_OPT { get; set; }
        public string SALE_ANLYS8_OPT { get; set; }
        public string PURC_ANLYS7_OPT { get; set; }
        public string PURC_ANLYS8_OPT { get; set; }
        public string MVMT_ANLYS7_OPT { get; set; }
        public string MVMT_ANLYS8_OPT { get; set; }
        public string JORD_ANLYS7_OPT { get; set; }
        public string JORD_ANLYS8_OPT { get; set; }
        public string AR_ANLYS1_OPT { get; set; }
        public string AR_ANLYS2_OPT { get; set; }
        public string AR_ANLYS3_OPT { get; set; }
        public string AR_ANLYS4_OPT { get; set; }
        public string AR_ANLYS5_OPT { get; set; }
        public string AR_ANLYS6_OPT { get; set; }
        public string AR_ANLYS7_OPT { get; set; }
        public string AR_ANLYS8_OPT { get; set; }
        public string AP_ANLYS1_OPT { get; set; }
        public string AP_ANLYS2_OPT { get; set; }
        public string AP_ANLYS3_OPT { get; set; }
        public string AP_ANLYS4_OPT { get; set; }
        public string AP_ANLYS5_OPT { get; set; }
        public string AP_ANLYS6_OPT { get; set; }
        public string AP_ANLYS7_OPT { get; set; }
        public string AP_ANLYS8_OPT { get; set; }
        public string ODBC { get; set; }
        public string MASTER_COMPANY { get; set; }
        public string ACCT_ANLYS5_OPT { get; set; }
        public string ACCT_ANLYS6_OPT { get; set; }
        public string ACCT_ANLYS7_OPT { get; set; }
        public string ACCT_ANLYS8_OPT { get; set; }
        public string ACCT_ANLYS9_OPT { get; set; }
        public string ACCT_ANLYS10_OPT { get; set; }
        public string ITEM_ANLYS5_OPT { get; set; }
        public string ITEM_ANLYS6_OPT { get; set; }
        public string ITEM_ANLYS7_OPT { get; set; }
        public string ITEM_ANLYS8_OPT { get; set; }
        public string ITEM_ANLYS9_OPT { get; set; }
        public string ITEM_ANLYS10_OPT { get; set; }
        public string CUST_ANLYS5_OPT { get; set; }
        public string CUST_ANLYS6_OPT { get; set; }
        public string CUST_ANLYS7_OPT { get; set; }
        public string CUST_ANLYS8_OPT { get; set; }
        public string CUST_ANLYS9_OPT { get; set; }
        public string CUST_ANLYS10_OPT { get; set; }
        public string VEND_ANLYS5_OPT { get; set; }
        public string VEND_ANLYS6_OPT { get; set; }
        public string VEND_ANLYS7_OPT { get; set; }
        public string VEND_ANLYS8_OPT { get; set; }
        public string VEND_ANLYS9_OPT { get; set; }
        public string VEND_ANLYS10_OPT { get; set; }
        public string SALE_ANLYS9_OPT { get; set; }
        public string SALE_ANLYS10_OPT { get; set; }
        public string SALE_ANLYS11_OPT { get; set; }
        public string SALE_ANLYS12_OPT { get; set; }
        public string SALE_ANLYS13_OPT { get; set; }
        public string SALE_ANLYS14_OPT { get; set; }
        public string SALE_ANLYS15_OPT { get; set; }
        public string SALE_ANLYS16_OPT { get; set; }
        public string SALE_ANLYS17_OPT { get; set; }
        public string SALE_ANLYS18_OPT { get; set; }
        public string SALE_ANLYS19_OPT { get; set; }
        public string SALE_ANLYS20_OPT { get; set; }
        public string PURC_ANLYS9_OPT { get; set; }
        public string PURC_ANLYS10_OPT { get; set; }
        public string PURC_ANLYS11_OPT { get; set; }
        public string PURC_ANLYS12_OPT { get; set; }
        public string PURC_ANLYS13_OPT { get; set; }
        public string PURC_ANLYS14_OPT { get; set; }
        public string PURC_ANLYS15_OPT { get; set; }
        public string PURC_ANLYS16_OPT { get; set; }
        public string PURC_ANLYS17_OPT { get; set; }
        public string PURC_ANLYS18_OPT { get; set; }
        public string PURC_ANLYS19_OPT { get; set; }
        public string PURC_ANLYS20_OPT { get; set; }
        public string MVMT_ANLYS9_OPT { get; set; }
        public string MVMT_ANLYS10_OPT { get; set; }
        public string MVMT_ANLYS11_OPT { get; set; }
        public string MVMT_ANLYS12_OPT { get; set; }
        public string MVMT_ANLYS13_OPT { get; set; }
        public string MVMT_ANLYS14_OPT { get; set; }
        public string MVMT_ANLYS15_OPT { get; set; }
        public string MVMT_ANLYS16_OPT { get; set; }
        public string MVMT_ANLYS17_OPT { get; set; }
        public string MVMT_ANLYS18_OPT { get; set; }
        public string MVMT_ANLYS19_OPT { get; set; }
        public string MVMT_ANLYS20_OPT { get; set; }
        public string JORD_ANLYS9_OPT { get; set; }
        public string JORD_ANLYS10_OPT { get; set; }
        public string JORD_ANLYS11_OPT { get; set; }
        public string JORD_ANLYS12_OPT { get; set; }
        public string JORD_ANLYS13_OPT { get; set; }
        public string JORD_ANLYS14_OPT { get; set; }
        public string JORD_ANLYS15_OPT { get; set; }
        public string JORD_ANLYS16_OPT { get; set; }
        public string JORD_ANLYS17_OPT { get; set; }
        public string JORD_ANLYS18_OPT { get; set; }
        public string JORD_ANLYS19_OPT { get; set; }
        public string JORD_ANLYS20_OPT { get; set; }
        public string AR_ANLYS9_OPT { get; set; }
        public string AR_ANLYS10_OPT { get; set; }
        public string AR_ANLYS11_OPT { get; set; }
        public string AR_ANLYS12_OPT { get; set; }
        public string AR_ANLYS13_OPT { get; set; }
        public string AR_ANLYS14_OPT { get; set; }
        public string AR_ANLYS15_OPT { get; set; }
        public string AR_ANLYS16_OPT { get; set; }
        public string AR_ANLYS17_OPT { get; set; }
        public string AR_ANLYS18_OPT { get; set; }
        public string AR_ANLYS19_OPT { get; set; }
        public string AR_ANLYS20_OPT { get; set; }
        public string AP_ANLYS9_OPT { get; set; }
        public string AP_ANLYS10_OPT { get; set; }
        public string AP_ANLYS11_OPT { get; set; }
        public string AP_ANLYS12_OPT { get; set; }
        public string AP_ANLYS13_OPT { get; set; }
        public string AP_ANLYS14_OPT { get; set; }
        public string AP_ANLYS15_OPT { get; set; }
        public string AP_ANLYS16_OPT { get; set; }
        public string AP_ANLYS17_OPT { get; set; }
        public string AP_ANLYS18_OPT { get; set; }
        public string AP_ANLYS19_OPT { get; set; }
        public string AP_ANLYS20_OPT { get; set; }
        public string VOCH_ANLYS9_OPT { get; set; }
        public string VOCH_ANLYS10_OPT { get; set; }
        public string VOCH_ANLYS11_OPT { get; set; }
        public string VOCH_ANLYS12_OPT { get; set; }
        public string VOCH_ANLYS13_OPT { get; set; }
        public string VOCH_ANLYS14_OPT { get; set; }
        public string VOCH_ANLYS15_OPT { get; set; }
        public string VOCH_ANLYS16_OPT { get; set; }
        public string VOCH_ANLYS17_OPT { get; set; }
        public string VOCH_ANLYS18_OPT { get; set; }
        public string VOCH_ANLYS19_OPT { get; set; }
        public string VOCH_ANLYS20_OPT { get; set; }
        public string OLAP_SERVER { get; set; }
        public string OLAP_DATABASE { get; set; }
        public DateTime? EXPIRY_DATE { get; set; }
        public int? MAX_USERS { get; set; }
    }
}